### ISSUE TITLE
Minimise docker image size

### ISSUE THREAD

**Issue by HenryQW** [BoKKeR/RSS-to-Telegram-Bot#1]
Hi, it appears the docker image size can be dramatically reduced by using python:3-alpine as base. Do you mind uploading the current dockerfile so I might be able to PR it? Thanks!

**Comment by HenryQW** [comment]
![image](https://user-images.githubusercontent.com/5896343/52515174-26966480-2c10-11e9-9c26-c5143c1a0190.png)

I've forked it [here](https://github.com/HenryQW/RSS-to-Telegram-Bot)

**Comment by BoKKeR** [comment]
Cool, sorry I didnt have time you can do a PR.
