### ISSUE TITLE
rss-feed settings are reset

### ISSUE THREAD

**Issue by toleeck** [BoKKeR/RSS-to-Telegram-Bot#11]
After the container is restarted, the rss-feed settings are reset.
Can this be avoided?
That is, after rebooting, the bot needs to add the RSS feed again.

**Comment by BoKKeR** [comment]
Hey! that is not the case on my end, are you sure you mean restart and not rebuild?

**Comment by toleeck** [comment]
Yes exactly. sorry.

> 
> 
> Hey! that is not the case on my end, are you sure you mean restart and not rebuild?

Yes exactly. sorry.

**Comment by BoKKeR** [comment]
If you want the database to persist updates/rebuilds you can specify a local volume for the database path

```
  -v /path/to/host/config:/config \
```
