### ISSUE TITLE
Feed title

### ISSUE THREAD

**Issue by temporhodes** [BoKKeR/RSS-to-Telegram-Bot#12]
Hello.
Thanks for the bot.

Right now the bot only sends the url of the feed items.
Is it possible to add feed title/feed image ( or custom imge ) to the bot ? with htmls tags for telegram.

Thanks.

**Comment by BoKKeR** [comment]
Do you have an example link with example data what you would want extracted? Can this be done programatically for every site or does this need to be parsed for each site separately ?

**Comment by temporhodes** [comment]
I have seen ifttt rss & integromat has it.plus kwgt android app does this too.
The format for extracting is general in all rss feeds i think.
for example this :
https://www.youtube.com/feeds/videos.xml?channel_id=UCi8e0iOVk1fEOogdfu4YgfA

it has : 
<title>
<media:title>
<media content url>
<media:thumbnail>
or this one : https://9gagrss.com/feed/
img src
title
pub date
==========
it would be great in this form 
<a href="img scr">🚫</a>\n
<a href="feed url">Feed item title</a>

thanks.

**Comment by tux93** [comment]
I'm understanding this as generating previews for the sent links, shouldn't Telegram do that itself?

**Comment by temporhodes** [comment]
> I'm understanding this as generating previews for the sent links, shouldn't Telegram do that itself?

yep.but some of my rss feeds are from private sources, and telegram doesnt generate anything.

**Comment by BoKKeR** [comment]
This is something that should be definitely implemented. We are already using feedparser so we would just need to check for additional properties. 

https://feedparser.readthedocs.io/en/latest/common-rss-elements.html 

I will see if I can carve out some time for it

**Comment by BoKKeR** [comment]
I have added feed title, there was no clear way of adding the picture.
