### ISSUE TITLE
XML support 

### ISSUE THREAD

**Issue by temporhodes** [BoKKeR/RSS-to-Telegram-Bot#14]
Hello.
Thanks for the great bot.
When i add rss links that ends with xml bot does'nt support it.

is it possible to add xml support ?!

thanks.

**Comment by BoKKeR** [comment]
Can you post a xml example link?

**Comment by temporhodes** [comment]
> Can you post a xml example link?

for example this link 
http://www.aljazeera.com/xml/rss/all.xml
or
https://www.buzzfeed.com/uk/index.xml

thanks.

**Comment by BoKKeR** [comment]
Both links work on my local instance and report news after a few hours. I used the https link for aljazeera. Xml is supported

**Comment by temporhodes** [comment]
yep.
i don't know why it doesnt work for some .xml links.
other rss feeds are fast and ok.but xml feeds have a little delay and stops after a while.
