### ISSUE TITLE
RSS Feed titles

### ISSUE THREAD

**Issue by temporhodes** [BoKKeR/RSS-to-Telegram-Bot#15]
Hello.thanks a lot for the bot...

right now bot only sends the link of the entries is rss feeds. 
is it possible to add entry title & published time for each feed item too?

thanks.

**Comment by toleeck** [comment]
A similar question was discussed here not so long ago https://github.com/BoKKeR/RSS-to-Telegram-Bot/issues/12

**Comment by temporhodes** [comment]
> A similar question was discussed here not so long ago #12

it doesnt show title for me.
somehow i copied the test feed pattern in .py file and replced in rss_monitor and now it shows.

```
context.bot.send_message(chatid, rss_d.entries[0]['title'] + "\n" + "\n" +
        rss_d.entries[0]['link'])
```

**Comment by temporhodes** [comment]
solved
