### ISSUE TITLE
cannot remove rss feeds

### ISSUE THREAD

**Issue by pfreeborn01** [BoKKeR/RSS-to-Telegram-Bot#18]
Hi,

the help file indicates that I can remove an RSS feed by typing:
/remove !Title!

Indeed, the bot returns a message to indicate that the title is removed, but it continues to remain in the database.
e.g.
/list 
continues to show all titles added, including the ones that I tried to remove.

**Comment by BoKKeR** [comment]
hm that is weird, do you see any logs? it works on my end

**Comment by pfreeborn01** [comment]
i don't have any logs, only what I see in the Telegram bot.  For example:

/add news_cnn  http://rss.cnn.com/rss/cnn_topstories.rss

added 
TITLE: news_cnn
RSS: http://rss.cnn.com/rss/cnn_topstories.rss

/remove !news_cnn!

Removed: !news_cnn!

/list

Title: news_cnn
rss url: http://rss.cnn.com/rss/cnn_topstories.rss
last checked article: http://rss.cnn.com/~r/rss/cnn_topstories/~3/-6xSFbBdqQg/index.html

**Comment by BoKKeR** [comment]
works for me with that url, can you check the logs from docker/python? Could you double check the databasee user permissions ?
