### ISSUE TITLE
SQL Injection everywhere

### ISSUE THREAD

**Issue by Lonami** [BoKKeR/RSS-to-Telegram-Bot#2]
[You have a little Bobby Tables](https://www.xkcd.com/327/) [all](https://github.com/BoKKeR/RSS-to-Telegram-Bot/blob/ec89f225e13dfb95b5fee7b0c6400d6e65dd4783/telegramRSSbot.py#L33) [over](https://github.com/BoKKeR/RSS-to-Telegram-Bot/blob/ec89f225e13dfb95b5fee7b0c6400d6e65dd4783/telegramRSSbot.py#L85) [your](https://github.com/BoKKeR/RSS-to-Telegram-Bot/blob/ec89f225e13dfb95b5fee7b0c6400d6e65dd4783/telegramRSSbot.py#L114) [code](https://github.com/BoKKeR/RSS-to-Telegram-Bot/blob/master/telegramRSSbot.py). You're not supposed to format with `%`. You're supposed to pass a tuple as the second parameter. Please read through [Python's `sqlite3` module documentation](https://docs.python.org/3/library/sqlite3.html):

> ```python
> # Never do this -- insecure!
> symbol = 'RHAT'
> c.execute("SELECT * FROM stocks WHERE symbol = '%s'" % symbol)
> 
> # Do this instead
> t = ('RHAT',)
> c.execute('SELECT * FROM stocks WHERE symbol=?', t)
> print(c.fetchone())
> ```

Thanks to @expectocode for finding this, not me.

**Comment by BoKKeR** [comment]
I am only using this script in an isolated chat/group where it is only me who can access the bot. But it is worth fixing for others. Thanks for the help
