### ISSUE TITLE
Bot is not forwarding any RSS feeds automatically

### ISSUE THREAD

**Issue by xdIceBear** [BoKKeR/RSS-to-Telegram-Bot#20]
Test works fine 
List works fine 
but the bot doesn't post feeds automatically to the groups

**Comment by BoKKeR** [comment]
Does it work if you add the bot yourself without a group?

**Comment by xdIceBear** [comment]
No it doesn't forward any feed automatically

**Comment by reggroux** [comment]
Its working for me.

**Comment by xdIceBear** [comment]
> Its working for me.

Does it forward automatically ? I get feeds only manually

**Comment by xdIceBear** [comment]
> Its working for me.

Bot works im sorry. ( https://elements.heroku.com/buttons/usmanmughalji/rss-feed-bot ) This Scrpt is the fault. I ran it on PC and works perfectly.
