### ISSUE TITLE
Need a command to dump all previous rss posts for first time setup

### ISSUE THREAD

**Issue by amosbird** [BoKKeR/RSS-to-Telegram-Bot#3]
Hi, I'm building an telegram-rss channel and it seems reasonable to have all previous messages of a rss feed posted to the channel at the first time. What do you think?

**Comment by BoKKeR** [comment]
This could be an additional feature. Separate command like 
`/getall` 
that would get all the RSS feed items and organize them based on time before printing the items out.

You can implement this feature and do a PR.

**Comment by alfonder** [comment]
For implementing this feature it needs to solve the 'known issue' first. I'm talking about the bug, that only 1 last item is posted even when there are several new ones.

**Comment by BoKKeR** [comment]
As there is not a lot of interest for this I am closing this. A limited implementation without rss-pagination support can be added fairly fast if there is interest
