### ISSUE TITLE
[feature request]

### ISSUE THREAD

**Issue by Haasie** [BoKKeR/RSS-to-Telegram-Bot#34]
It it possible to add persistence storage?
Now sometime after reboot i need to add the links again.

**Comment by BoKKeR** [comment]
Check the readme, mount a volume according to it

**Comment by Haasie** [comment]
Volume is in place already. Should i make the .conf file with the feeds in it myself?

Thank you

**Comment by BoKKeR** [comment]
No the database should be created in that folder upon running the container, do you see the database?

**Comment by Haasie** [comment]
Hello Bokker,

Thank you for your reply.
I reviewed the template for the docker container I used and saw that /app/ was missing in front of /config/.
Rerun the the template and now the database is created. Thank you for your help and sorry for your time.
Really appreciate your project!

**Comment by BoKKeR** [comment]
No worries! I appreciate it!
