### ISSUE TITLE
ERROR: connection refused/not valid RSS link

### ISSUE THREAD

**Issue by ronilaukkarinen** [BoKKeR/RSS-to-Telegram-Bot#35]
> ERROR: connection refused/not valid RSS link
if you think this is a mistake [open an issue](https://github.com/BoKKeR/RSS-to-Telegram-Bot/issues) with the given link

What's wrong with these links:

https://www.rollekino.fi/feed/?post_type=movie
https://www.rollekino.fi/leffat/feed

I don't get it why they wouldn't work. They're perfectly valid.

**Comment by BoKKeR** [comment]
I tried and both links work for me, but I cant add them the same time. Which version are you running ?

**Comment by ronilaukkarinen** [comment]
Oh right, I had the main feed added so that's why I guess? I removed the main feed and it now let's add one of these. The main feed is https://www.rollekino.fi/feed

There should be a way to add multiple feeds from the same domain. I have several post types that I want to use with the bot, now only one is possible to add to it.

**Comment by BoKKeR** [comment]
Should be fixed in 2.0.3, give it a try
