### ISSUE TITLE
The bot only posts links

### ISSUE THREAD

**Issue by desertkun** [BoKKeR/RSS-to-Telegram-Bot#36]
For example, this RSS feed https://nitter.net/Nrg8000/rss

The bot only posts links from that RSS and that's it. No images no text.

**Comment by BoKKeR** [comment]
You are free to open a PR

**Comment by Rongronggg9** [comment]
Try https://github.com/Rongronggg9/RSS-to-Telegram-Bot

**Comment by desertkun** [comment]
> Try https://github.com/Rongronggg9/RSS-to-Telegram-Bot

Wow, that's not even a fork? Thanks I'll check it out.

**Comment by Rongronggg9** [comment]
> > Try [Rongronggg9/RSS-to-Telegram-Bot](https://github.com/Rongronggg9/RSS-to-Telegram-Bot)
> 
> Wow, that's not even a fork? Thanks I'll check it out.

https://github.com/Rongronggg9/RSS-to-Telegram-Bot#license

> The repository is formerly a fork of [BoKKeR/RSS-to-Telegram-Bot](https://github.com/BoKKeR/RSS-to-Telegram-Bot). They have been entirely different projects since the early days of this project.

**Comment by desertkun** [comment]
Thanks! Yeah it works much better. I'll keep the issue open for future finders
