### ISSUE TITLE
ERROR: connection refused/not valid RSS link

### ISSUE THREAD

**Issue by Phaeton** [BoKKeR/RSS-to-Telegram-Bot#37]
I am trying to add (https://rpilocator.com/feed/?country=US&cat=PI4) but keep getting the not valid error. I've validated it with a few different sites and it seems to be setup OK.

**Comment by BoKKeR** [comment]
The link works for me, I used this command to add it `/add rpilocator https://rpilocator.com/feed/?country=US&cat=PI4`

**Comment by Phaeton** [comment]
It's working now. Strange. I added feeds before and after it. I am sure it was user error on my part. Thanks for checking and maintaining the project. I like this project as it seems to be less resource hungry. 

When I run /help it shows version as `vundefined`. I'm running in Docker with a fresh pull from today.

**Comment by BoKKeR** [comment]
Thanks for the kind words I really appreciate it! I think I forgot to deploy the version text fix ;)
