### ISSUE TITLE
My rss is not allow

### ISSUE THREAD

**Issue by billouetaudrey** [BoKKeR/RSS-to-Telegram-Bot#39]
Hello, I try to add this rss : https://www.extreme-down.io/rss.xml

But not working 

Any idea ?

Thanks

**Comment by billouetaudrey** [comment]
PS : Other xml working fine

**Comment by BoKKeR** [comment]
It’s the same problem as issue #38 . Cloud flare is blocking the bot from accessing the link

**Comment by billouetaudrey** [comment]
Oh ok sorry

**Comment by BoKKeR** [comment]
No problem, I see that other bots have the same
