### ISSUE TITLE
Different RSS feeds in multiple groups. 

### ISSUE THREAD

**Issue by DrNion** [BoKKeR/RSS-to-Telegram-Bot#4]
Is it possible to add multiple chatIDs in order to separate the RSS feeds into different groups (for me it would be general RSS with YouTube)?
Coping the Git folder didn't work for me (changed the name of the folder and the telegramRSSbot.py script though which might caused the problem).
A solution I had in my mind: dumping all chatIDs into the script and choosing later in the telegram app during the /add procedure one of those IDs.
I'm not a developer so I cannot talk about practical details :)

**Comment by BoKKeR** [comment]
Right now this is not possible, I made the script for my own use only and this was not in the scope, but what you could do is just run multiple instances of the script using different. chatID-s,  but that would probably require multiple bots to work. 

To implement this on the code we would need to save the RSS feeds separately for each chatID, and maybe implement a queue system for fetching items.

**Comment by Rongronggg9** [comment]
Try: https://github.com/Rongronggg9/RSS-to-Telegram-Bot

Disclaimer: The project was formerly a fork of this project, but since it aims differently, I detached it.

**Comment by BoKKeR** [comment]
Great work @Rongronggg9 but could you reference the original project in your repo as the license states? 
I will probably look into this issue soon

**Comment by Rongronggg9** [comment]
> Great work @Rongronggg9 but could you reference the original project in your repo as the license states? I will probably look into this issue soon

Sure.

https://github.com/Rongronggg9/RSS-to-Telegram-Bot/commit/d8438943d4ab879d66f78b8dc0dec6ef8cdcd596#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R108

**Comment by BoKKeR** [comment]
There is some support for this in the develop branch for now, but @Rongronggg9-s implementation is more polished 🌟
