### ISSUE TITLE
Bot does not work with Bungie RSS links

### ISSUE THREAD

**Issue by nealhead** [BoKKeR/RSS-to-Telegram-Bot#41]
Examples:

https://www.bungie.net/7/en/News/destiny
https://www.bungie.net/7/en/news?page=1&FILENAME=NewsRss&LOCALE=en
http://www.bungie.net/News/NewsRss.ashx

**Comment by BoKKeR** [comment]
Those links dont seem RSS at all?

**Comment by nealhead** [comment]
How does this one look?

https://www.bungie.net/en/Rss/NewsByCategory

**Comment by BoKKeR** [comment]
That link works with the bot. but their url-s are incomplete, "/7/en/News/Article/official-destiny-2-guide-new"
